version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloakpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_THEME: mytheme
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - ./keycloak/mytheme:/opt/keycloak/themes/mytheme

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OAUTH2_PROVIDER_URL=http://keycloak:8080/realms/myrealm
    ports:
      - "5000:5000"
    depends_on:
      - keycloak
      - postgres
    networks:
      - my_network

  frontend:
    container_name: frontend
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
      - keycloak
      - postgres
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge